# 生产环境配置
environment: prod

web:
  base_url: "${env:WEB_BASE_URL}" # 从环境变量获取生产环境 Web URL
  timeout: ${env:DEFAULT_TIMEOUT:-30} # (覆盖默认值: 30秒回退)
  screenshot_on_failure: false # (覆盖默认值: false)
  # URL 成功模式 (环境特定配置)
  urls:
    success_patterns:
      - "/workbench/workbench-manage"

api:
  base_url: "${env:API_BASE_URL}" # 从环境变量获取生产环境 API URL
  timeout: ${env:DEFAULT_TIMEOUT:-30} # (环境特定配置或覆盖默认)
  verify_ssl: true # (环境特定配置或覆盖默认)
  retry_attempts: 3 # (环境特定配置或覆盖默认)
  # 支付相关配置 (环境特定配置)
  payment:
    key: "${env:PROD_PAYMENT_API_KEY}"
    mch_id: "${env:PROD_MCH_ID}"
    device_info: "${env:PROD_DEVICE_INFO}"

# 登录信息 (环境特定配置, 引用生产环境变量)
credentials:
  admin:
    username: "${env:PROD_ADMIN_USERNAME}"
    password: "${env:PROD_ADMIN_PASSWORD}"
  default:
    username: "${env:PROD_DEFAULT_USERNAME}"
    password: "${env:PROD_DEFAULT_PASSWORD}"

# 生产环境邮件配置
notification:
  email:
    enabled: ${env:EMAIL_ENABLED:-true} # (覆盖默认值: true回退)
    # 邮件模板 (环境特定配置)
    templates:
      alert: "生产环境告警模板"
      report: "生产环境测试报告模板"

# 日志设置
log:
  level: "${env:LOG_LEVEL:-WARNING}" # (覆盖默认值: WARNING回退)
  console:
    color: false # (覆盖默认值: false)
    # 控制台其他配置继承 settings.yaml
  file:
    path: "logs/prod" # (覆盖默认值)
    max_size: 50 # (覆盖默认值: 50MB)
    backup_count: 10 # (覆盖默认值: 10个)
    # 文件日志其他配置继承 settings.yaml

# 性能监控配置 (环境特定配置)
monitoring:
  enabled: true
  metrics_collection_interval: 60 # 秒
  alert_threshold:
    response_time: 2000 # 毫秒
    error_rate: 0.01 # 1% 