# 测试环境配置
environment: test

web:
  base_url: "${env:WEB_BASE_URL}" # 从环境变量获取测试环境 Web URL
  headless: ${env:HEADLESS:-false} # (覆盖默认值: false)
  timeout: ${env:DEFAULT_TIMEOUT:-15} # (覆盖默认值: 15秒回退)
  slow_mo: ${env:SLOW_MO:-100} # (覆盖默认值: 100毫秒)
  # URL 成功模式 (环境特定配置)
  urls:
    success_patterns:
      - "/omp/workbench/workbench-manage"


api:
  base_url: "${env:API_BASE_URL}" # 从环境变量获取测试环境 API URL
  timeout: ${env:DEFAULT_TIMEOUT:-15} # (环境特定配置或覆盖默认)
  verify_ssl: true # (环境特定配置或覆盖默认)
  retry_attempts: 2 # (环境特定配置或覆盖默认)
  # 支付相关配置 (环境特定配置)
  payment:
    key: "${env:PAYMENT_API_KEY}"
    mch_id: "${env:PAYMENT_MCH_ID}"
    device_info: "${env:PAYMENT_DEVICE_INFO}"

# 登录信息 (环境特定配置, 引用测试环境变量)
credentials:
  admin:
    username: "${env:TEST_ADMIN_USERNAME}"
    password: "${env:TEST_ADMIN_PASSWORD}"
  default:
    username: "${env:TEST_DEFAULT_USERNAME}"
    password: "${env:TEST_DEFAULT_PASSWORD}"

# 测试环境邮件配置
notification:
  email:
    enabled: ${env:EMAIL_ENABLED:-true} # (覆盖默认值: true回退)
    # 邮件模板 (环境特定配置)
    templates:
      test_success: "测试成功通知模板"
      test_failure: "测试失败通知模板"

# 日志设置
log:
  level: "${env:LOG_LEVEL:-DEBUG}" # (覆盖默认值: DEBUG回退)
  console:
    enabled: true # <-- Correct format: Set enabled explicitly
  file:
    path: "${env:LOG_FILE_PATH}" # (覆盖默认值，使用环境变量)
    max_size: 20 # (覆盖默认值: 20MB)
    # 文件日志其他配置继承 settings.yaml 