# 通用基础配置，会被环境配置和环境变量覆盖
web:
  output:
    directory: "output/web" # 默认输出目录
  timeouts:
    default: ${env:DEFAULT_TIMEOUT:-10} # 默认超时时间(秒)
  screenshot:
    on_failure: true # 默认在失败时截图

# 通用邮件默认配置 (环境可覆盖)
notification:
  email:
    enabled: ${env:EMAIL_ENABLED:-false} # 默认禁用
    use_ssl: ${env:EMAIL_USE_SSL:-true}
    smtp_port: ${env:EMAIL_SMTP_PORT:-465} # 常用 SSL 端口
    pop3_port: ${env:EMAIL_POP3_PORT:-995} # 常用 SSL 端口
    pop3_use_ssl: ${env:EMAIL_POP3_USE_SSL:-true}

# 日志配置 (环境可覆盖)
log:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: ${env:LOG_LEVEL:-INFO} # 根日志级别
  file:
    enabled: ${env:LOG_FILE_ENABLED:-true}
    path: ${env:LOG_FILE_PATH:-output/logs/${env:APP_ENV:-dev}}
    max_size: 10 # MB
    backup_count: 5
  console:
    enabled: ${env:LOG_CONSOLE_ENABLED:-true}
    color: false
  # 新增：为特定 logger 设置级别，以减少冗余日志输出
  loggers:
    src.utils.signature:
      level: INFO
    src.utils.data_generator:
      level: INFO
    # 您可以根据需要添加更多 logger，例如 tests.api.conftest 等
    # tests.api.conftest:
    #  level: WARNING

# 浏览器默认配置 (环境可覆盖)
browser:
  default: ${env:BROWSER:-chromium}
  headless: ${env:HEADLESS:-true}
  slow_mo: ${env:SLOW_MO:-0} # 毫秒

# 截图配置 (环境可覆盖)
screenshot:
  output_dir: ${env:SCREENSHOT_DIR:-output/screenshots}
  report_dir: ${env:REPORT_SCREENSHOT_DIR:-output/reports/screenshots}

# ================================ 
# App & WeChat Testing Configuration 
# ================================ 
airtest:
  timeouts:
    default: ${env:AIRTEST_DEFAULT_TIMEOUT:-20} # Airtest/Poco 操作默认超时时间 (秒)

app:
  # 设备 URI (如果所有平台用同一个设备)
  # device_uri: ${env:MOBILE_DEVICE_URI:-Android:///} # 这个保持注释或移除
  jiyu:
    package_name: ${env:JIYU_APP_PACKAGE_NAME:-com.example.jiyuapp} # 提供一个示例默认值
    # 如果 Jiyu 需要独立设备 URI
    device_uri: ${env:JIYU_DEVICE_URI:-Android:///} # <-- 取消注释并引用 JIYU_DEVICE_URI, 提供默认值
  wechat:
    package_name: ${env:WECHAT_PACKAGE_NAME:-com.tencent.mm} # 微信包名通常固定
    targets:
      mini_program: ${env:WECHAT_MINI_PROGRAM_TARGET:-CMpark智慧停车}
      official_account: ${env:WECHAT_OFFICIAL_ACCOUNT_TARGET:-CMpark招商享停车}
    # 如果微信需要独立设备 URI
    device_uri: ${env:WECHAT_DEVICE_URI:-Android:///} # <-- 取消注释并引用 WECHAT_DEVICE_URI, 提供默认值
  payment:
    activity_suffix: ${env:EXPECTED_PAYMENT_ACTIVITY_SUFFIX:-.framework.app.UIPageFragmentActivity}
