web:
  output:
    directory: "output/web"  # 输出文件保存目录
  # 通用框架设置示例 (具体值通常由项目或环境配置覆盖)
  timeouts:
    page_load: 10
    element_wait: 2
    # 移除了特定页面的 state_stabilize 和 success_check

# 注意: 所有特定于应用程序 UI 的选择器 (Selectors) 
# 应该由使用此框架的具体项目在其自己的配置文件中定义。
# 这个核心 settings.yaml 不应包含与特定 UI 强耦合的选择器。

# 示例: 项目特定的配置文件 (例如 project_config.yaml) 可能包含如下内容:
# login_page:
#   selectors:
#     username_input: "input[name='username']"
#     password_input: "input[name='password']"
#     login_button: "button#login"
# dashboard_page:
#   selectors:
#     welcome_message: ".welcome"

  login:
    captcha:
      test_override: ${TEST_CAPTCHA_VALUE}  # 从环境变量获取
      max_attempts: 3
      retry_interval: 1
      wait_after_input: 1
      wait_for_refresh: 0.5
      min_length: 4
    timeouts:
      page_load: 10
      element_wait: 2
      state_stabilize: 0.5
      success_check: 2
    urls:
      success_patterns:
        - "/omp/home"
        - "/omp/index"
    selectors:
      username_input: "input[type='text'][placeholder='用户名']"
      password_input: "input[type='password']"
      captcha_input: "input[type='text'][maxlength='4'][placeholder='验证码']"
      captcha_image: "img[src*='api/captcha/getCode']"
      login_button: "button.el-button.login-form__btn"
      error_message: ".el-message--error"
      validation_error_selectors:
        - ".is-invalid"
        - "[aria-invalid='true']"
        - ".error"
        - ".has-error"
      adjacent_error_selectors:
        - ".error-message"
        - ".invalid-feedback"
        - ".form-error"
      error_indicators:
        - ".ant-message-error"

  dashboard: # 添加 dashboard 配置段
    selectors:
      welcome_message: "h1.welcome, .welcome-message, .dashboard-welcome"
      user_info: ".user-info, .profile-summary"
      dashboard_content: ".dashboard-content, .main-content"
      notification_panel: ".notifications, .alert-panel"
      # 导航栏选择器
      nav_root: "nav.main-nav, .navbar, header"
      home_link: "${web.dashboard.selectors.nav_root} a.home, ${web.dashboard.selectors.nav_root} a[href*='home']"
      profile_link: "${web.dashboard.selectors.nav_root} a.profile, ${web.dashboard.selectors.nav_root} a[href*='profile']"
      settings_link: "${web.dashboard.selectors.nav_root} a.settings, ${web.dashboard.selectors.nav_root} a[href*='settings']"
      logout_button: "${web.dashboard.selectors.nav_root} a.logout, ${web.dashboard.selectors.nav_root} button.logout, ${web.dashboard.selectors.nav_root} a[href*='logout']"