# 通用基础配置，会被环境配置和环境变量覆盖
web:
  output:
    directory: "output/web" # 默认输出目录
  timeouts:
    default: ${env:DEFAULT_TIMEOUT:-10} # 默认超时时间(秒)
  screenshot:
    on_failure: true # 默认在失败时截图

# 通用邮件默认配置 (环境可覆盖)
notification:
  email:
    enabled: ${env:EMAIL_ENABLED:-false} # 默认禁用
    use_ssl: ${env:EMAIL_USE_SSL:-true}
    smtp_port: ${env:EMAIL_SMTP_PORT:-465} # 常用 SSL 端口
    pop3_port: ${env:EMAIL_POP3_PORT:-995} # 常用 SSL 端口
    pop3_use_ssl: ${env:EMAIL_POP3_USE_SSL:-true}

# 日志配置 (环境可覆盖)
log:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: ${env:LOG_LEVEL:-INFO}
  file:
    enabled: ${env:LOG_FILE_ENABLED:-true}
    path: ${env:LOG_FILE_PATH:-output/logs/${env:APP_ENV:-dev}}
    max_size: 10 # MB
    backup_count: 5
  console:
    enabled: ${env:LOG_CONSOLE_ENABLED:-true}
    color: true

# 浏览器默认配置 (环境可覆盖)
browser:
  default: ${env:BROWSER:-chromium}
  headless: ${env:HEADLESS:-true}
  slow_mo: ${env:SLOW_MO:-0} # 毫秒

# 截图配置 (环境可覆盖)
screenshot:
  output_dir: ${env:SCREENSHOT_DIR:-output/screenshots}
  report_dir: ${env:REPORT_SCREENSHOT_DIR:-output/reports/screenshots}
